export const ATTACK_ICONS = {
  multiattack: "",
  claw: "",
  sword: "",
  arrow_target: "",
  hammer: "",
  bite: "",
  slam: "",
  whirlwind: "",
  tail: "",
  unarmed_strike: "",
  melee: "",
  ranged_attack: "",
  sneak_attack: "",
  uncanny_dodge: "",
  cunning_action: "",
  second_wind: "",
  action_surge: "",
  dual_personalities: "",
  expertise: "",
};
