export const CONDITION_ICONS = {
  blinded: "",
  charmed: "",
  deafened: "",
  frightened: "",
  grappled: "",
  incapacitated: "",
  invisible: "",
  paralyzed: "",
  petrified: "",
  poisoned: "",
  prone: "",
  restrained: "",
  stunned: "",
  unconscious: "",
  exhaustion: "",
};
