export const CREATURE_TYPE_ICONS = {
  aberration: "",
  beast: "",
  celestial: "",
  construct: "",
  dragon: "",
  dragons: "",
  elemental: "",
  fey: "",
  fiend: "",
  giant: "",
  humanoid: "",
  monstrosity: "",
  ooze: "",
  plant: "",
  undead: "",
  ghost: "",
};
