export const DAMAGE_TYPE_ICONS = {
  slashing: "",
  piercing: "",
  bludgeoning: "",
  fire: "",
  cold: "",
  lightning: "",
  thunder: "",
  poison: "",
  acid: "",
  psychic: "",
  necrotic: "",
  radiant: "",
  force: "",
};
