export const FIGHTING_STYLE_ICONS = {
  fighter_fighting_style_archery: "",
  fighter_fighting_style_defense: "",
  fighter_fighting_style_dueling: "",
  fighter_fighting_style_great_weapon_fighting: "",
  fighter_fighting_style_protection: "",
  fighter_fighting_style_two_weapon_fighting: "",
  arcane_trickster: "",
  thief: "",
  assassin: "",
  champion: "",
  battle_master: "",
  eldritch_knight: "",
  psi_warrior: "",
};
