export const SKILL_ICONS: Record<string, string> = {
  acrobatics: "",
  animal_handling: "",
  arcana: "",
  athletics: "",
  deception: "",
  history: "",
  insight: "",
  intimidation: "",
  investigation: "",
  medicine: "",
  nature: "",
  perception: "",
  performance: "",
  persuasion: "",
  religion: "",
  sleight_of_hand: "",
  stealth: "",
  survival: "",
};
