export const SUBCLASS_ICONS = {
  arcane_trickster: "",
  assassin: "",
  battle_master: "",
  berserker: "",
  champion: "",
  devotion: "",
  draconic: "",
  eldritch_knight: "",
  evocation: "",
  fiend: "",
  hunter: "",
  land: "",
  life: "",
  lore: "",
  open_hand: "",
  psi_warrior: "",
  thief: "",
};
