import test from 'node:test';
import assert from 'node:assert/strict';
import {
  shouldTriggerDiscovery,
  isDiscoveryIssue,
  formatCandidateFollowUpIssue,
  formatDiscoveryReport,
  validateDiscoveryReport,
  executeDiscoveryAudit,
  persistDiscoveryReportIssue
} from './jules-discovery-loop.mjs';
import { selectDispatchableIssue } from './jules-issue-selector.mjs';
import { validateIssueQualityGate } from './jules-issue-validator.mjs';

test('shouldTriggerDiscovery returns true only when readyIssues <= 2 AND activeDiscovery === 0', () => {
  assert.equal(shouldTriggerDiscovery({ readyIssuesCount: 2, activeDiscoveryCount: 0 }), true);
  assert.equal(shouldTriggerDiscovery({ readyIssuesCount: 0, activeDiscoveryCount: 0 }), true);
  assert.equal(shouldTriggerDiscovery({ readyIssuesCount: 3, activeDiscoveryCount: 0 }), false);
  assert.equal(shouldTriggerDiscovery({ readyIssuesCount: 1, activeDiscoveryCount: 1 }), false);
});

test('shouldTriggerDiscovery fails closed on missing, invalid, negative, or non-integer inputs', () => {
  assert.equal(shouldTriggerDiscovery(), false);
  assert.equal(shouldTriggerDiscovery(null), false);
  assert.equal(shouldTriggerDiscovery({ readyIssuesCount: undefined, activeDiscoveryCount: 0 }), false);
  assert.equal(shouldTriggerDiscovery({ readyIssuesCount: '2', activeDiscoveryCount: 0 }), false);
  assert.equal(shouldTriggerDiscovery({ readyIssuesCount: -1, activeDiscoveryCount: 0 }), false);
  assert.equal(shouldTriggerDiscovery({ readyIssuesCount: 2, activeDiscoveryCount: -1 }), false);
  assert.equal(shouldTriggerDiscovery({ readyIssuesCount: 1.5, activeDiscoveryCount: 0 }), false);
});

test('isDiscoveryIssue detects discovery issues strictly by canonical markers (label or title)', () => {
  assert.equal(isDiscoveryIssue({ title: '[Discovery] Audit repo' }), true);
  assert.equal(isDiscoveryIssue({ title: 'Feature', labels: [{ name: 'discovery' }] }), true);
  assert.equal(isDiscoveryIssue({ title: 'Feature', labels: ['discovery'] }), true);
  // Ordinary issue containing investigation section is NOT misclassified as Discovery
  assert.equal(isDiscoveryIssue({ title: 'Normal Issue', body: '## Repository Investigation\nChecked codebase.' }), false);
});

test('formatCandidateFollowUpIssue produces status: proposed metadata', () => {
  const candidateText = formatCandidateFollowUpIssue({
    problem: 'Missing test suite.',
    goal: 'Proposed feature',
    facts: '- `src/index.ts` exists',
    investigation: 'Audit',
    ownership: 'Architecture',
    risks: 'None',
    scope: '- Scope',
    acceptance: '1. Criteria',
    verification: '- Test',
    references: ['docs/WORKFLOW.md'],
    outOfScope: 'Out of scope',
    priority: 40,
    specialist: 'architecture'
  });

  assert.match(candidateText, /\*\*status:\*\* proposed/);
  assert.doesNotMatch(candidateText, /\*\*status:\*\* ready/);

  // Proposed candidate issue should fail quality gate for status ready dispatch
  const gateResult = validateIssueQualityGate(candidateText, { fileExistFn: () => true });
  assert.equal(gateResult.valid, false);
  assert.ok(gateResult.errors.some(e => e.includes('status must be "ready"')));
});

test('validateDiscoveryReport validates all required discovery contract sections', () => {
  const validReport = formatDiscoveryReport({
    goal: 'Audit repository for gaps.',
    investigation: 'Inspected scripts.',
    evidence: 'Found 2 unlinked modules.',
    findings: 'Module X is unused.',
    risk: 'Low risk.',
    candidates: '- Propose issue for module X cleanup.',
    rejected: '- None.'
  });

  const result = validateDiscoveryReport(validReport);
  assert.equal(result.valid, true);

  const invalidReport = validReport.replace('## Rejected / Non-actionable Findings\n- None.', '');
  const invalidResult = validateDiscoveryReport(invalidReport);
  assert.equal(invalidResult.valid, false);
  assert.ok(invalidResult.errors.some(e => e.includes('Rejected / Non-actionable Findings')));
});

test('end-to-end safety invariant: candidate generated by discovery cannot be selected or dispatched', () => {
  const candidateBody = formatCandidateFollowUpIssue({
    problem: 'Discovered gap in module X.',
    goal: 'Remediate gap in module X.',
    facts: '- `src/moduleX.ts` exists.',
    investigation: 'Audit of module X.',
    ownership: 'Architecture',
    risks: 'Low risk.',
    scope: '- `src/moduleX.ts`',
    acceptance: '1. Module X is tested.',
    verification: '- `npm test`',
    references: ['docs/WORKFLOW.md'],
    outOfScope: 'Refactoring unrelated modules.',
    priority: 50,
    specialist: 'architecture'
  });

  const candidateIssue = {
    number: 999,
    title: 'chore(moduleX): fix discovered gap',
    body: candidateBody,
    state: 'open'
  };

  // Run candidate through selectDispatchableIssue
  const selection = selectDispatchableIssue([candidateIssue], { fileExistFn: () => true });

  assert.equal(selection.selected, null);
  assert.ok(selection.rejected.some(r => r.issueNumber === 999 && r.reason.includes('Failed Quality Gate')));
  assert.equal(selection.discovery.triggered, true);
});

test('executeDiscoveryAudit creates report and candidate issues with deep evidence inspection', () => {
  const auditResult = executeDiscoveryAudit([], {
    readyIssuesCount: 0,
    fileExistFn: () => true,
    readFileFn: path => path.includes('WORKFLOW')
      ? 'Issue Quality Contract v2'
      : path.includes('PHASE_SAFETY_GATE')
        ? 'Issue Quality Gate'
        : 'Inspect before implementing'
  });

  assert.equal(auditResult.executed, true);
  assert.ok(auditResult.report);
  assert.ok(auditResult.discoveryIssue);
  assert.equal(auditResult.discoveryIssue.title, '[Discovery] Repository Evidence Audit Report');
  assert.deepEqual(auditResult.discoveryIssue.labels, ['discovery']);
  assert.equal(auditResult.report, auditResult.discoveryIssue.body);
  assert.equal(validateDiscoveryReport(auditResult.discoveryIssue.body).valid, true);
});

test('persistDiscoveryReportIssue calls GitHub REST API to create Discovery Report issue', async () => {
  let createdPayload = null;
  const mockFetch = async (url, options) => {
    assert.equal(url, 'https://api.github.com/repos/japiohopman/artificer/issues');
    assert.equal(options.method, 'POST');
    assert.equal(options.headers.Authorization, 'Bearer mock-token');
    createdPayload = JSON.parse(options.body);
    return {
      ok: true,
      json: async () => ({ number: 500, ...createdPayload })
    };
  };

  const discoveryIssue = {
    title: '[Discovery] Repository Evidence Audit Report',
    body: '## Goal\nAudit',
    labels: ['discovery']
  };

  const created = await persistDiscoveryReportIssue(discoveryIssue, 'mock-token', 'japiohopman/artificer', mockFetch);
  assert.equal(created.number, 500);
  assert.equal(createdPayload.title, '[Discovery] Repository Evidence Audit Report');
  assert.deepEqual(createdPayload.labels, ['discovery']);
});

test('persistDiscoveryReportIssue fails closed when GitHub API fails or inputs are missing', async () => {
  await assert.rejects(
    () => persistDiscoveryReportIssue(null, 'token', 'repo'),
    /discoveryIssue, token, and repo are required/
  );

  const mockFailingFetch = async () => ({
    ok: false,
    status: 403,
    text: async () => 'Forbidden'
  });

  const discoveryIssue = { title: '[Discovery] Test', body: 'Body', labels: ['discovery'] };

  await assert.rejects(
    () => persistDiscoveryReportIssue(discoveryIssue, 'token', 'repo', mockFailingFetch),
    /Failed to create Discovery Report GitHub Issue: 403 Forbidden/
  );
});
