import { ai, MODELS } from "./config";

export async function generateCodexImage(
  name: string, 
  type: string, 
  size?: string, 
  alignment?: string, 
  subtype?: string, 
  lore?: string,
  category: 'monsters' | 'materials' | 'equipment' | 'characters' = 'monsters'
): Promise<string | null> {
  try {
    const details = category === 'monsters' 
      ? `a ${size || ""} ${alignment || ""} ${type} ${subtype ? `(${subtype})` : ""}`
      : category === 'characters'
      ? `a level ${subtype || "1"} ${type} named ${name}`
      : `a ${type} named ${name}`;
    
    // If lore looks like a full cinematic prompt (generated by generateVisualPrompt),
    // use it directly or as the primary core.
    let fullPrompt = "";
    const isFullPrompt = lore && (lore.includes("high-fidelity") || lore.includes("cinematic digital painting"));
    
    let specificStyle = "";
    let aspectRatio: "1:1" | "3:4" | "4:3" | "9:16" | "16:9" | "3:2" = "3:2";
    
    if (category === 'characters') {
      const level = parseInt(subtype || "1");
      const isHighLevel = level >= 10;
      const isMidLevel = level >= 5;
      
      let characterStyle = "The character should be rendered as a realistic D&D adventurer. Focus on period-accurate materials like worn leather, forged steel, and textured fabrics.";
      
      if (isHighLevel) {
        characterStyle = "The character is a LEGENDARY HERO. Their equipment is highly ornate, featuring intricate engravings, subtle magical glowing runes, and prestigious materials like mithral or dragon-leather. Their expression is battle-hardened and wise. The character radiates an aura of immense power and experience.";
      } else if (isMidLevel) {
        characterStyle = "The character is an EXPERIENCED ADVENTURER. Their gear is high-quality and well-maintained, but shows signs of many travels. Add some refined details like silver filigree or specialized tool belts. They look confident and capable.";
      } else {
        characterStyle = "The character is a NOVICE TRAVELER. Their equipment is basic and functional—raw leather, simple iron, and sturdy canvas. They look eager but relatively fresh-faced and less seasoned.";
      }
      
      specificStyle = characterStyle;
      aspectRatio = "3:4";
    }

    if (category === 'monsters') {
      const typeLower = type.toLowerCase();
      const subtypeLower = (subtype || "").toLowerCase();
      const sizeLower = (size || "").toLowerCase();
      const isTinyOrSmall = sizeLower.includes('tiny') || sizeLower.includes('small');
      
      if (typeLower.includes('beast')) {
        if (isTinyOrSmall) {
          specificStyle = "The creature MUST be rendered as a realistic, natural, and adorable animal. Focus on soft fur, expressive but natural eyes, and a docile or curious posture. ABSOLUTELY NO monstrous features, NO glowing runes, NO horrific mutations, NO aggressive spikes, NO demonic elements. It should look like a high-quality nature documentary photograph turned into a painting.";
        } else {
          specificStyle = "The creature MUST be rendered as a realistic, powerful natural animal. Focus on organic textures, realistic anatomy, and natural lighting. Avoid overly magical or demonic embellishments unless specified in the lore. It should feel like a legendary beast from a high-fantasy world, but grounded in biology.";
        }
      } else if (typeLower.includes('celestial')) {
        specificStyle = "The creature should radiate divine majesty and ethereal beauty. Focus on radiant light, golden or pearlescent textures, and a sense of serene power. It can have subtle glowing elements or holy auras.";
      } else if (typeLower.includes('fiend')) {
        if (subtypeLower.includes('demon')) {
          specificStyle = "DEMONIC STYLE: Chaotic, bizarre, and terrifying. Focus on asymmetrical features, multiple eyes or limbs, raw fleshy textures, and horrific mutations. It should feel unpredictable and visceral. Use Abyssal motifs.";
        } else if (subtypeLower.includes('devil')) {
          specificStyle = "INFERNAL STYLE: Sinister, majestic, and law-bound. Focus on clean but menacing lines, red or obsidian skin, symmetrical proportions, elegant horns, and a sense of cruel authority. Use Infernal jewelry or armor motifs.";
        } else {
          specificStyle = "FIENDISH STYLE: The creature should look horrific, gritty, and menacing. Focus on dark textures, glowing malevolent eyes, and jagged, aggressive features. It should feel dangerous and unnatural.";
        }
      } else if (typeLower.includes('undead')) {
        specificStyle = "UNDEAD STYLE: The creature should look horrific, gritty, and decaying. Focus on dark textures, glowing malevolent eyes, and jagged, aggressive features. It should feel dangerous and unnatural.";
      }
    }

    if (category === 'materials') {
      const nameLower = name.toLowerCase();
      const typeLower = type.toLowerCase();
      
      // Map category to instructions
      if (typeLower.includes('herb')) {
        specificStyle = "The material MUST be presented as a freshly picked botanical specimen (sprig, leaf, or root). It should look organic, raw, and harvested. ABSOLUTELY NO leather straps, NO labels, NO furniture, NO props. Focus on natural plant textures.";
      } else if (typeLower.includes('monster part')) {
        specificStyle = "The material MUST be presented as a raw organic component from a legendary creature (e.g. scale, eye, horn, tooth, or vial of blood). It should look like a visceral trophy but raw and un-decorated. Focus on exotic biology and gritty textures.";
      } else if (typeLower.includes('oil')) {
        specificStyle = "The material MUST be presented as an elegant glass vial or bottle containing a translucent fluid. Focus on light refraction, fluid viscosity, and the craftsmanship of the glass.";
      } else if (typeLower.includes('consumable')) {
        specificStyle = "The material MUST be presented as the item itself (e.g. food or basic ration). Focus on realistic, gritty textures of the object. NO environment or context.";
      } else if (typeLower.includes('bundled')) {
        specificStyle = "The material MUST be presented as a neatly tied bundle wrapped with simple twine. Focus on the organized stack and the texture of the material being bundled.";
      } else if (nameLower.includes('metal') || typeLower.includes('metal') || nameLower.includes('ingot') || nameLower.includes('bar')) {
        specificStyle = "The material MUST be presented as a solid, rectangular ingot or bar of metal. Focus on its metallic luster, sharp edges, and realistic reflections. NO text or engravings on the metal.";
      } else if (nameLower.includes('ore') || typeLower.includes('ore') || nameLower.includes('chunk') || nameLower.includes('raw')) {
        specificStyle = "The material MUST be presented as a raw, jagged chunk of ore. Focus on the contrast between the rocky stone matrix and the embedded mineral veins. NO text or labels.";
      } else if (nameLower.includes('wood') || typeLower.includes('wood') || nameLower.includes('log') || nameLower.includes('plank')) {
        specificStyle = "The material MUST be presented as a cut log or a thick plank of wood. Focus on the natural grain, bark texture, and organic rings. NO text or carvings.";
      } else {
        specificStyle = "Focus on the material's texture, essence, and physical properties. The image should highlight the raw beauty of the material. NO text or labels.";
      }
      specificStyle += " NO characters, NO people, NO hands, NO creatures in the image.";
      aspectRatio = "9:16";
    } else if (category === 'equipment') {
      // Tier detection from name or lore
      const nameLower = name.toLowerCase();
      const isTier1 = nameLower.includes('+1') || nameLower.includes('uncommon');
      const isTier2 = nameLower.includes('+2') || nameLower.includes('rare');
      const isTier3 = nameLower.includes('+3') || nameLower.includes('legendary') || nameLower.includes('very rare');
      
      let tierStyle = "Focus on the item's craftsmanship and functional detail (e.g., forged steel, worn leather, polished wood). The item should be presented as a high-quality, realistic object.";
      
      if (isTier3) {
        tierStyle = "This is a LEGENDARY ARTIFACT. It should look incredibly ornate and powerful. Add pulsing magical energy cores, brilliant glowing runes that illuminate the item, floating ethereal particles, and exotic legendary materials like celestial gold or void-iron. The item should radiate an intense, awe-inspiring magical aura.";
      } else if (isTier2) {
        tierStyle = "This is a RARE MASTERWORK item. It should feature intricate engravings filled with glowing magical energy, superior polished surfaces, and a distinct magical presence. Add subtle visual effects like faint swirling energy or shimmering surfaces that suggest significant magical power.";
      } else if (isTier1) {
        tierStyle = "This is an UNCOMMON MAGICAL item. It should look like high-quality gear but with subtle magical enhancements. Add fine silver/gold filigree, a couple of glowing runes, or a faint, clean magical sheen that distinguishes it from mundane equipment.";
      }

      specificStyle = `${tierStyle} NO text, NO labels, NO characters, NO people, NO hands.`;
      aspectRatio = "9:16";
    }

    if (isFullPrompt) {
        // If we have a full prompt, we prioritize it
        fullPrompt = lore!;
    } else {
        const loreContext = lore ? `Lore context: ${lore}. ` : "";
        fullPrompt = `A high-fidelity, cinematic digital painting of ${name}, ${details}. 
        ${loreContext}
        ${specificStyle}`;
    }
    
    // Add critical background rules of they are not already there
    const backgroundRules = `
    CRITICAL BACKGROUND RULE: 
    - The background MUST be a 100% solid, flat, matte, uniform chroma key green (#00FF00) from edge to edge.
    - THE SUBJECT MUST BE THE ONLY THING IN THE IMAGE.
    - NO floors, NO walls, NO arches, NO ceilings, NO furniture, NO props, NO environment.
    - NO shadows on the background, NO gradients, NO lighting effects on the background.
    - NO VIGNETTE, NO BORDERS, NO FRAME, NO EDGE DARKENING, NO CORNER SHADOWS.
    - The green background must be perfectly uniform with no lighting falloff.
    - The subject should appear as if it is floating in a pure, flat green digital void.`;

    const finalPrompt = fullPrompt.includes("#00FF00") ? fullPrompt : `${fullPrompt}\n${backgroundRules}\n
    ART STYLE: Cinematic, Baldur's Gate 3 / classic D&D style, adult-themed, gritty texture. 
    COMPOSITION: Centered, dynamic pose. 
    NO text, NO labels, NO characters, NO people, NO hands.
    NO cartoon, NO mobile game, NO low-quality, NO kids style.`;

    const response = await ai.models.generateContent({
      model: MODELS.IMAGE,
      contents: {
        parts: [{ text: finalPrompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as any
        },
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    return null;
  } catch (error) {
    console.error("Error generating image:", error);
    return null;
  }
}

export async function generateBackgroundImage(
  type: string, 
  variation: number = 0, 
  instruction: string = '',
  isSmallAnimal: boolean = false
): Promise<string | null> {
  try {
    const isMacro = isSmallAnimal || variation === 4;
    const isWide = variation === 3;
    
    const perspective = isMacro 
      ? "MACRO PERSPECTIVE: A extreme low-angle, ground-level 'ant's eye view'. The camera is placed directly on the soil/floor. Focus on the micro-details of the immediate foreground: individual blades of grass, detailed pebbles, moss textures, and low-lying roots. The background should have a shallow depth of field with a beautiful bokeh effect, making the environment feel vast but seen from a tiny creature's height. The horizon line should be very high or obscured by foreground elements." 
      : isWide
      ? "WIDE PERSPECTIVE: An epic, zoomed-out, wide-angle shot with a massive sense of scale. The camera is placed far back to capture the vastness of the environment. Focus on grand landmarks, distant horizons, and a deep depth of field. This is a 'god's eye view' or a distant observer's view, perfect for showcasing huge, gargantuan entities. The environment should feel immense and overwhelming in its scale."
      : "CINEMATIC PERSPECTIVE: A wide-angle, epic landscape view with a broad horizon and deep depth of field. Focus on the grand scale of the environment.";

    const habitatDescriptions: Record<string, string[]> = {
      air: [
        "a vast, cinematic sky with swirling clouds, distant floating peaks, and ethereal light rays",
        "a clear, bright blue sky with a few distant birds soaring and a radiant sun",
        "a dramatic sky at sunset with vibrant orange and purple clouds over distant mountain silhouettes",
        "a stormy, dark sky with heavy grey clouds and flashes of distant lightning",
        "a mystical sky with floating islands, waterfalls falling into the void, and a giant moon"
      ],
      water: [
        "a deep, atmospheric underwater scene with ancient ruins, kelp forests, and shimmering light from the surface",
        "a shallow coral reef with vibrant tropical fish, clear turquoise water, and bright sunlight",
        "a dark, abyssal trench with bioluminescent creatures and jagged volcanic vents",
        "a murky swamp underwater scene with tangled roots, sunken logs, and green-tinted light",
        "a frozen underwater scene with ice floes above and crystal clear, cold blue water"
      ],
      land_forest: [
        "a dark, ancient forest with gnarled trees, glowing moss, and misty shadows",
        "a sun-dappled woodland with tall oaks, a carpet of bluebells, and a peaceful atmosphere",
        "a dense pine forest in the morning mist with shafts of light piercing the canopy",
        "a vibrant autumn forest with red and gold leaves, a winding path, and crisp air",
        "a magical fey forest with oversized mushrooms, glowing butterflies, and twisted silver trees"
      ],
      land_urban: [
        "a gritty, gothic city street at night with cobblestones, flickering lanterns, and imposing stone architecture",
        "a bustling medieval marketplace with colorful stalls, timber-framed houses, and a lively atmosphere",
        "a grand palace square with marble fountains, statues, and majestic white stone buildings",
        "a narrow, dark alleyway with steam rising from vents and shadows lurking in doorways",
        "a ruined city street with collapsed buildings, overgrown vines, and a sense of desolation"
      ],
      land_plains: [
        "a sweeping, windswept plain with tall golden grass, distant mountains, and a dramatic sunset sky",
        "a peaceful meadow with wildflowers, a small stream, and rolling green hills",
        "a harsh, dry savanna with scattered acacia trees and a shimmering heat haze",
        "a vast farmland with rows of wheat, a distant farmhouse, and a clear blue sky",
        "a mystical plain with ancient standing stones and a sky filled with multiple moons"
      ],
      land_mountains: [
        "a jagged, snow-capped mountain range with steep cliffs, rocky outcrops, and a cold, clear atmosphere",
        "a high mountain pass with a narrow winding path and a view of a valley below",
        "a volcanic mountain peak with glowing lava flows and a sky filled with ash and smoke",
        "a rocky mountain plateau with sparse vegetation and a dramatic thunderstorm approaching",
        "a mystical mountain with floating peaks connected by stone bridges"
      ],
      jungle: [
        "a dense, vibrant jungle with massive ferns, hanging vines, ancient ruins, and shafts of light piercing the canopy",
        "a tropical rainforest with a hidden waterfall and a lush, green environment",
        "a dark, dangerous jungle with carnivorous plants and eyes glowing in the shadows",
        "a jungle river scene with a slow-moving current and overhanging trees",
        "a prehistoric jungle with giant leaves and distant sounds of massive creatures"
      ],
      desert: [
        "a vast, scorching desert with shifting sand dunes, ancient pyramids, and a shimmering heat haze",
        "a rocky desert canyon with steep red walls and a narrow strip of sky above",
        "a desert oasis with palm trees, a small pool of water, and a sense of relief",
        "a night-time desert scene with a vast starry sky and cold blue shadows on the dunes",
        "a desert wasteland with bleached bones and ruins half-buried in the sand"
      ],
      underdark: [
        "a dark, subterranean world with bioluminescent fungi, jagged stalactites, and mysterious underground rivers",
        "a massive underground cavern with a drow city built into the walls",
        "a narrow tunnel system with glowing crystals and narrow ledges over deep chasms",
        "a fungal forest in a cave with spores floating in the air",
        "an underground lake with still, black water and ancient stone carvings"
      ],
      beach: [
        "a cinematic tropical beach with white sand, turquoise water, palm trees, and a bright, clear sky",
        "a rugged, rocky coastline with crashing waves and a lighthouse in the distance",
        "a beach at twilight with a glowing bioluminescent tide and a crescent moon",
        "a stormy beach with dark sand, grey waves, and a piece of driftwood",
        "a mystical beach with glass-like sand and strange, crystalline rock formations"
      ],
      church: [
        "a solemn, gothic church interior with stained glass windows, rows of pews, and shafts of light illuminating dust motes",
        "a ruined cathedral with a collapsed roof and nature reclaiming the stone",
        "a small, humble village chapel with wooden beams and a warm, inviting atmosphere",
        "a dark, occult temple with flickering candles, strange altars, and a sense of dread",
        "a celestial temple with white marble, golden accents, and a sky visible through the dome"
      ],
      castle: [
        "a grand, imposing castle courtyard with stone walls, banners fluttering in the wind, and a sense of ancient power",
        "a dark, forbidding castle throne room with a massive stone throne and iron chandeliers",
        "a castle battlements scene with a view of the surrounding lands and a sunset sky",
        "a ruined castle keep with crumbling walls and a sense of lost glory",
        "a magical floating castle with towers touching the clouds"
      ],
      fort: [
        "a rugged, fortified military outpost with wooden palisades, watchtowers, and a harsh, defensive atmosphere",
        "a stone fortress built into a mountainside with heavy iron gates",
        "a desert fort with adobe walls and a central well",
        "a coastal fort with cannons overlooking the sea",
        "a ruined fort with broken walls and abandoned equipment"
      ],
      ruins: [
        "the crumbling remains of an ancient civilization, with overgrown stone pillars, collapsed arches, and a sense of lost history",
        "a desert ruin with half-buried statues and sand-worn inscriptions",
        "a jungle ruin with vines strangling the stone and hidden traps",
        "an underwater ruin with coral growing on the walls and fish swimming through windows",
        "a mountain ruin with snow-covered stones and a cold, lonely atmosphere"
      ],
      cave: [
        "a natural limestone cave with dripping stalactites and a small pool of clear water",
        "a dark, damp cave with moss-covered walls and a narrow entrance",
        "a crystalline cave with glowing minerals and a magical atmosphere",
        "a volcanic cave with heat haze and glowing cracks in the floor",
        "a massive sea cave with the sound of waves echoing through the chambers"
      ],
      snowy: [
        "a vast, frozen tundra with a blanket of deep snow and a cold, grey sky",
        "a snowy pine forest with branches heavy with frost and a peaceful silence",
        "a frozen lake with a smooth, icy surface and distant snow-capped mountains",
        "a blizzard scene with swirling snow and limited visibility",
        "a magical ice palace with crystalline walls and a shimmering aurora borealis"
      ],
      swamp: [
        "a murky, fog-filled swamp with stagnant water, gnarled cypress trees, and hanging moss",
        "a vibrant swamp with colorful lilies, dragonflies, and a lush green environment",
        "a dark, dangerous swamp with bubbling mud pits and strange lights in the distance",
        "a swamp river with a slow current and tangled roots along the banks",
        "a ruined swamp village with half-sunken huts and a sense of decay"
      ],
      dragon_cave: [
        "a massive, treasure-filled dragon's lair with piles of gold, jewels, and ancient artifacts",
        "a scorched dragon cave with blackened walls and the smell of sulfur",
        "a dragon's nest with large, leathery eggs and a bed of soft furs",
        "a dragon cave with a view of the valley below from a high ledge",
        "a mystical dragon cave with ancient carvings and a sense of primordial power"
      ],
      fey: [
        "a whimsical fey realm with pastel-colored plants, floating bubbles, and a magical twilight sky",
        "a fey garden with oversized flowers, singing birds, and a sense of wonder",
        "a dark fey forest with deceptive paths and mischievous spirits",
        "a fey palace made of living wood and woven vines",
        "a fey meadow with dancing lights and a sky filled with colorful nebulae"
      ],
      volcano: [
        "a dramatic volcanic landscape with flowing lava, ash-filled skies, and glowing obsidian rocks",
        "the interior of a volcano with bubbling magma pools and intense heat haze",
        "a scorched volcanic plain with steam vents and jagged basalt formations",
        "a volcanic crater lake with dark, steaming water and sulfurous yellow edges",
        "a ruined obsidian fortress built on the edge of a lava river"
      ],
      ethereal: [
        "a ghostly, translucent realm with swirling mists, floating spirits, and a sense of weightlessness",
        "an ethereal plane with shimmering curtains of light and distant, blurred shapes",
        "a mystical void with glowing ley lines and floating crystalline structures",
        "a haunted ethereal landscape with echoes of the material world seen through a veil",
        "a bridge of pure light crossing a vast, starry abyss"
      ],
      void: [
        "a dark, infinite void with swirling purple and black energies and distant, dying stars",
        "a desolate void landscape with floating debris and a sense of absolute isolation",
        "a chaotic void storm with flashes of eldritch light and distorted reality",
        "a quiet, empty void with a single, glowing portal in the distance",
        "a void temple made of shadow and starlight"
      ]
    };

    const descriptions = habitatDescriptions[type] || ["a cinematic fantasy landscape"];
    const description = descriptions[variation % descriptions.length];
    const prompt = `A high-fidelity, cinematic digital painting of ${description}${instruction ? `, specifically ${instruction}` : ''}. 
    ${perspective}
    
    ART STYLE: Cinematic, Baldur's Gate 3 / classic D&D style, adult-themed, gritty texture, atmospheric lighting. 
    COMPOSITION: Landscape orientation (approx 3:2 aspect ratio). Wide shot, immersive environment.
    NO characters, NO monsters, NO subjects. This is a background plate.
    NO cartoon, NO mobile game, NO low-quality, NO kids style.`;

    const response = await ai.models.generateContent({
      model: MODELS.IMAGE,
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9"
        },
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    return null;
  } catch (error) {
    console.error("Error generating background image:", error);
    return null;
  }
}

export async function generateVisualPrompt(
  item: any, 
  category: 'monsters' | 'materials' | 'equipment' = 'monsters'
): Promise<string> {
  try {
    const wikiUrl = category === 'monsters' 
      ? `https://forgottenrealms.fandom.com/wiki/${item.name?.replace(/\s+/g, '_')}#Description`
      : `https://forgottenrealms.fandom.com/wiki/${item.name?.replace(/\s+/g, '_')}`;
    
    const details = category === 'monsters'
      ? `a ${item.size || ""} ${item.alignment || ""} ${item.type} ${item.subtype ? `(${item.subtype})` : ""}`
      : `a ${item.category || item.type || 'item'}`;
    
    let promptInstructions = "";
    let aspectRatio = "3:2";
    
    if (category === 'monsters') {
      const typeLower = (item.type || "").toLowerCase();
      const sizeLower = (item.size || "").toLowerCase();
      const isTinyOrSmall = sizeLower.includes('tiny') || sizeLower.includes('small');
      
      let beastInstruction = "";
      if (typeLower.includes('beast')) {
        if (isTinyOrSmall) {
          beastInstruction = "The creature MUST be described as a realistic, natural, and adorable animal. Focus on soft fur, expressive but natural eyes, and a docile or curious posture. ABSOLUTELY NO monstrous features, NO glowing runes, NO horrific mutations. It should look like a high-quality nature documentary photograph.";
        } else {
          beastInstruction = "The creature MUST be described as a realistic, powerful natural animal. Focus on organic textures and realistic anatomy. Avoid overly magical or demonic embellishments.";
        }
      }
      
      promptInstructions = `${beastInstruction} Focus the physical description on specific details from the wiki (like the aboleth's three eyes, four tentacles, lamprey-like mouth, etc.) and its stats/abilities.`;
      aspectRatio = "3:2";
    } else if (category === 'materials') {
      const nameLower = (item.name || '').toLowerCase();
      const typeLower = (item.category || item.type || '').toLowerCase();
      let shapeInstruction = "";
      
      if (typeLower.includes('herb')) {
        shapeInstruction = "The material MUST be presented as a freshly picked botanical specimen (sprig, leaf, or root). It should look organic, raw, and harvested. ABSOLUTELY NO leather straps, NO labels, NO furniture, NO props. Focus on natural plant textures.";
      } else if (typeLower.includes('monster part')) {
        shapeInstruction = "The material MUST be presented as a raw organic component from a legendary creature (e.g. scale, eye, horn, tooth, or vial of blood). It should look like a visceral trophy but raw and un-decorated. Focus on exotic biology and gritty textures.";
      } else if (typeLower.includes('oil')) {
        shapeInstruction = "The material MUST be presented as an elegant glass vial or bottle containing a translucent fluid. Focus on light refraction, fluid viscosity, and the craftsmanship of the glass.";
      } else if (typeLower.includes('consumable')) {
        shapeInstruction = "The material MUST be presented as the item itself (e.g. food or basic ration). Focus on realistic, gritty textures of the object. NO environment or context.";
      } else if (typeLower.includes('bundled')) {
        shapeInstruction = "The material MUST be presented as a neatly tied bundle wrapped with simple twine. Focus on the organized stack and the texture of the material being bundled.";
      } else if (nameLower.includes('metal') || typeLower.includes('metal') || nameLower.includes('ingot') || nameLower.includes('bar')) {
        shapeInstruction = "The material MUST be presented as a solid, rectangular ingot or bar of metal. NO text or engravings on the metal.";
      } else if (nameLower.includes('ore') || typeLower.includes('ore') || nameLower.includes('chunk') || nameLower.includes('raw')) {
        shapeInstruction = "The material MUST be presented as a raw, jagged chunk of ore. NO text or labels.";
      } else if (nameLower.includes('wood') || typeLower.includes('wood') || nameLower.includes('log') || nameLower.includes('plank')) {
        shapeInstruction = "The material MUST be presented as a cut log or a thick plank of wood. NO text or carvings.";
      }
      
      promptInstructions = `${shapeInstruction} Focus on the material's texture, essence, and physical properties. Describe how it looks in its raw or refined form (e.g., shimmering scales, polished essence, ancient bone). Highlight the unique physical properties that make it valuable. NO text, NO labels, NO characters, NO people, NO hands, NO furniture.`;
      aspectRatio = "9:16";
    } else if (category === 'equipment') {
      const nameLower = (item.name || '').toLowerCase();
      const getRarity = (r: any) => {
        if (!r) return "";
        if (typeof r === 'string') return r.toLowerCase();
        if (typeof r === 'object') return (r.name || r.value || "").toLowerCase();
        return "";
      };
      const rarity = getRarity(item.rarity);
      const isTier1 = nameLower.includes('+1') || rarity === 'uncommon';
      const isTier2 = nameLower.includes('+2') || rarity === 'rare';
      const isTier3 = nameLower.includes('+3') || (rarity === 'legendary' || rarity === 'very rare');
      
      let tierInstruction = "Focus on the item's craftsmanship and functional detail. Describe the materials it's made of and its overall aesthetic (e.g., forged steel, worn leather, polished wood). Emphasize its utility and realistic appearance.";
      
      if (isTier3) {
        tierInstruction = "This is a LEGENDARY ARTIFACT. Describe immense, radiating magical power. Mention ornate, intricate draconic or celestial motifs, deep engravings that glow with blinding white or golden light, and exotic materials like Adamantine or Mithral fused with magical energy cores. The item should look divine or anciently powerful.";
      } else if (isTier2) {
        tierInstruction = "This is a RARE MASTERWORK item. Describe superior craftsmanship with elegant engravings that shimmer with magical energy. Mention a noticeable magical aura or faint particles of energy surrounding the item. The item should look exceptionally well-made and obviously enchanted.";
      } else if (isTier1) {
        tierInstruction = "This is an UNCOMMON MAGICAL item. Describe high-quality materials with subtle magical touches, like a few glowing runes along the edge or a faint, clean magical sheen. It should look better than standard gear but not overly ornate.";
      }

      promptInstructions = `${tierInstruction} NO text, NO labels, NO characters, NO people, NO hands.`;
      aspectRatio = "9:16";
    }

    const itemCopy = { ...item };
    const description = item.wikiData?.Description || item.wikiData?.description || "";
    const lore = item.lore || "";
    
    if (itemCopy.wikiData) delete itemCopy.wikiData;
    if (itemCopy.lore) delete itemCopy.lore;
    if (itemCopy.imageUrl) delete itemCopy.imageUrl;
    
    const response = await ai.models.generateContent({
      model: MODELS.TEXT,
      contents: `Based on the following ${category} JSON, its lore, and specific physical description (supplemented by your knowledge of D&D lore from ${wikiUrl}), create a highly detailed, fantastic visual manifestation prompt for image generation.
      
      ${category.toUpperCase()} JSON: ${JSON.stringify(itemCopy)}
      LORE SUMMARY: ${lore}
      PHYSICAL DESCRIPTION FROM WIKI: ${description}
      
      The prompt MUST follow this structure:
      "A high-fidelity, cinematic digital painting of [detailed physical description], ${details}. 
      
      CRITICAL BACKGROUND RULE: 
      - The background MUST be a 100% solid, flat, matte, uniform chroma key green (#00FF00) from edge to edge.
      - THE SUBJECT MUST BE THE ONLY THING IN THE IMAGE.
      - NO floors, NO walls, NO arches, NO ceilings, NO furniture, NO props, NO environment.
      - NO shadows on the background, NO gradients, NO lighting effects on the background.
      - NO VIGNETTE, NO BORDERS, NO FRAME, NO EDGE DARKENING, NO CORNER SHADOWS.
      - The green background must be perfectly uniform with no lighting falloff.
      - The subject should appear as if it is floating in a pure, flat green digital void.
      
      ART STYLE: Cinematic, Baldur's Gate 3 / classic D&D style, adult-themed, gritty texture. 
      COMPOSITION: Centered, dynamic pose. Aspect ratio ${aspectRatio}."
      
      ${promptInstructions} Ensure the description is vivid and cinematic.`,
    });
    return response.text || "";
  } catch (error) {
    console.error("Error generating visual prompt:", error);
    return "";
  }
}
